config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    get 'change', to: 'users/registrations#change'
  end
  
  root 'pages#index'
  get '/search', to: 'users#search'
  resources :users, only: :show
  resources :posts, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_comment_form.html.erb
<div id="comment_form">
  <%= form_for(@comment) do |f| %>
    <%= f.hidden_field :post_id, value: feed_item.id %>
    <div class="content-form">
      <%= f.text_field :content, placeholder: "コメントを追加..." %>
    </div>
    <div class="submit-btn">
      <%= f.submit "投稿する", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/shared/_favorite.html.erb
<%= form_for(current_user.favorites.build, remote: true) do |f| %>
  <%= hidden_field_tag :post_id, feed_item.id %>
  <%= button_tag type: "submit", class: "btn" do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>

app/views/shared/_favorite_form.html.erb
<div id=<%= "favorite_form-#{feed_item.id}" %>>
  <% if current_user.favorite?(feed_item) %>
    <%= render 'shared/unfavorite', { feed_item: feed_item } %>
  <% else %>
    <%= render 'shared/favorite', { feed_item: feed_item } %>
  <% end %>
</div>

app/views/shared/_feed.html.erb
<div class="article">
  <% @feed_items.each do |feed_item| %>
    <div class="item">
      <div class="feed-header user-icon-mini">
        <%= image_tag feed_item.user.image.url %>
        <%= link_to feed_item.user.username, feed_item.user %>
      </div>
      <div class="article-img">
        <%= image_tag feed_item.picture.url %>
      </div>
      <div class="etc">
        <div class="icon-nav">
          <div class="favorite">
            <%= render 'shared/favorite_form', { feed_item: feed_item } %>
          </div>
          <div class="post-delete">
            <% if current_user == feed_item.user %>
              <%= link_to icon("far", "trash-alt"), feed_item, method: :delete,
                                  data: { confirm: "投稿を削除しますか" } %>
            <% end %>
          </div>
        </div>
        <div class="comments">
          <div class="comment-item">
            <% feed_item.comments.each do |comment| %>
            <div class="comment">
              <p><%= link_to comment.user.username, comment.user %></p>
              <p class="content"><%= comment.content %></p>
              <p class="delete">
                <% if current_user == comment.user %>
                  <%= link_to icon("far", "trash-alt"), comment, method: :delete, 
                                      data: { confirm: "コメントを削除しますか" } %>
                <% end %>
              </p>
            </div>
              
            <% end %>
          </div>
          <div class="comment_form">
            <%= render 'shared/comment_form', {feed_item: feed_item } %>
          </div>
        </div>
      </div>
    </div>
    
  <% end %>
</div>

app/views/shared/_notice.html.erb
<% if check_notification.blank? %>
  <%= link_to icon("far", "bell"), notifications_path %>
<% else %>
  <%= link_to icon("fas", "bell"), notifications_path %>
<% end %>

app/views/shared/_search-form.html.erb
<%= form_tag(search_path, method: :get) do %>
  <%= text_field_tag :search %>
  <%= button_tag type: "submit", class: "btn" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_tag(search_path, method: :get) do %>
  <%= text_field_tag :search %>
  <%= button_tag type: "submit", class: "btn" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

app/views/shared/_unfavorite.html.erb
<%= form_for(current_user.favorites.find_by(post_id: feed_item.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= button_tag type: "submit", class: "btn" do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% end %>